obs:
  mode: auto  # options: auto, websocket, apple_script
  recording_path: "/Users/Shared/OBSRecordings"  # as defined in OBS Studio
  websocket_host: "localhost"  # as defined in OBS Studio
  websocket_port: 4455  # as defined in OBS Studio
  websocket_password: "your_password"  # as defined in OBS Studio

transcription:
  model: "small"  # options: tiny, base, small, medium, large

ollama:
  model: "gpt-oss"  # options: gpt-oss, phi4, llama2, mistral, etc.

google_drive:
  enabled: true  # options: true, false
  folder_id: "your_google_drive_folder_id"
